---
title: "Advanced Stats - Bank Swallow Movement"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
date: "2023-04-24"

---

```{r setup, include=FALSE}
# Clear the R workspace environment
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/Manon/Documents/BIO8940 - Advanced Statistics/FinalProject') #set the working directory

```
## BIO8940 Final Project
### Bank swallow movements to roosting habitat
### By: Manon Veselovsky - 8259387
### Introduction:
#### 

```{r,include=FALSE}

########### LOAD DATA FILES AND LIBRARIES ##########

# #load data files on bank swallow movement
#departure = read.csv("data/departure_dat.csv") #UNCOMMENT TO LOAD CLIMATE DATA AND RUN SECTION 1.1 TO PROCESS DATA

depart_final = read.csv("data/departure_final.csv") #This is the dataset AFTER loading climate variables (done in section 1.1). Retrieving the NCEP climate data takes a long time for each variable (~1h) - skip the climate data retrieving section 1.1 by using this dataset

#load necessary libraries
library(lmerTest) #for glmer
library(car) #for Anova
library(RNCEP) #climate database
library(suncalc) #moon phase/illumination package
library(ggplot2) #for plotting
library(dplyr) #for number of distinct individuals/ids
library(effects) #for effects plots
library(performance) #for diagnostic plots on glmer - normality of random variables
library(DHARMa) #diagnostic plot for dispersion (over/under)
library(datawizard) #for scaling and centering
library(tidyverse) #for data management/processing

```


``` {r, include=FALSE}
############## Section 1.1:  CLIMATE VARIABLES FOR MOVEMENT DATA ########################

# #PLEASE NOTE: RETRIEVING THE CLIMATE DATA TAKES ~1 HOUR PER VARIABLE - this code is included but can be skipped by loading the included data file "depart_final" - line 23
# #IF YOU WISH TO RETRIEVE THE CLIMATE DATA YOURSELF BELOW PLEASE UNCOMMENT & LOAD THE FILE departure_dat.csv (LINE 21) AND UNCOMMENT THE SECTION BELOW


# # get surface air temperature at the detected time and location of the bird (data interpolated between weather stations and between times)
# departure$air_temp <- NCEP.interp.surface('air.sig995', departure$lat2, departure$lon2, departure$time_departure, reanalysis2 = FALSE, interpolate.space = TRUE, interpolate.time = TRUE, keep.unpacking.info = FALSE, return.units = TRUE,interp = 'IDW', p = 1, status.bar=FALSE)

# # get precipitable water (total amount) (kg/m^2) in the air at time of detection - same interpolation
# departure$precip <- NCEP.interp.surface('pr_wtr.eatm', departure$lat2, departure$lon2, departure$time_departure, reanalysis2 = TRUE, interpolate.space = TRUE, interpolate.time = TRUE, keep.unpacking.info = FALSE, return.units = TRUE,interp = 'IDW', p = 1, status.bar=FALSE)

# # get the precipitation rate for 6 hours after the departure time (kg/m^2/s, equivalent to mm/s); same interpolation
# departure$precip_rate <- NCEP.interp.gaussian('prate.sfc',departure$lat2, departure$lon2, departure$time_departure, reanalysis2 = TRUE, interpolate.space = TRUE, interpolate.time = TRUE, keep.unpacking.info = FALSE, return.units = TRUE,interp = 'IDW', p = 1, status.bar=FALSE)

# # Get total cloud cover, in %, for the location of bird detection - same interpolation
# departure$cloud_cover <- NCEP.interp.gaussian('tcdc.eatm', departure$lat2, departure$lon2, departure$time_departure, reanalysis2 = TRUE, interpolate.space = TRUE, interpolate.time = TRUE, keep.unpacking.info = FALSE, return.units = TRUE,interp = 'IDW', p = 1, status.bar=FALSE)

# # get the East-West wind component
# departure$uwind <- NCEP.interp.surface('uwnd.sig995', departure$lat2, departure$lon2, departure$time_departure, reanalysis2 = TRUE, interpolate.space = TRUE, interpolate.time = TRUE, keep.unpacking.info = FALSE, return.units = TRUE, interp = 'IDW', p = 1, status.bar=TRUE)

# #Get the North/South wind component
# departure$vwind <- NCEP.interp.surface('vwnd.sig995', departure$lat2, departure$lon2, departure$time_departure, reanalysis2 = FALSE, interpolate.space = TRUE, interpolate.time = TRUE, keep.unpacking.info = FALSE, return.units = TRUE, interp = 'IDW', p = 1, status.bar=TRUE)

# # assign the final, processed database to depart_final
# depart_final = departure

```

```{r}
#################### SECTION 1.2 VARIABLE MODIFICATIONS + SCALED DATABASE ################

# convert air temperature from Kelvin to degrees Celsius
depart_final$temp <- depart_final$air_temp - 273

#get lunar illumination (fraction of the moon that is illuminated) and moon phase at the time the bird was observed (movement to roost could be linked to availability of light)
depart_final$moon = getMoonIllumination(depart_final$time_departure,keep=c("fraction","phase"))

# create a variable for sky illumination by combining cloud cover and illumination of the moon (moon fraction) --> a full moon has a moon fraction of 1; illum will be maximum (100%) when the moon is full and cloud cover is 0
depart_final$illum = depart_final$moon.fraction*(100-depart_final$cloud_cover)

#convert precipitation rate from mm/s (= kg/m^2/s) to mm/h
depart_final$precip_mmh = depart_final$precip_rate*60*60

# make bird ID read as a factor, not integer
depart_final$id = as.factor(depart_final$id)

#set up a scaled database using standardize from data_wizard (reduces problems in glmer compared to scale())
df.scale = standardize(depart_final,select=c("distance","ordinal_date"))

scale_dist = scale(depart_final$distance)
scaleList_dist <- list(scale = attr(scale_dist, "scaled:scale"),
    center = attr(scale_dist, "scaled:center"))

scale_date = scale(depart_final$ordinal_date)
scaleList_date = list(scale = attr(scale_date, "scaled:scale"),
    center = attr(scale_date, "scaled:center"))

```


```{r, echo=FALSE}

####################### SECTION 1.3 EXPLORE VARIABLES #############################

# Plot the probability of roosting in the wetland complex against the distance from the colony to the wetland complex
ggplot(depart_final, aes(x=distance, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Distance to roost site (km)") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous(limit=c(25,90), breaks=c(30,40,50,60,70,80,90)) + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

# Plot the probability of roosting in the wetland complex against the ordinal date in the season
ggplot(depart_final, aes(x=ordinal_date, y=roost)) + facet_grid(~sex) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Ordinal date") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous(limit=c(150,200), breaks=c(150,160,170,180,190,200)) + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

# Plot the probability of roosting in the wetland complex against the surface air temperature
ggplot(depart_final, aes(x=temp, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Air temperature (deg C)") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous(breaks=c(15,20,25,30)) + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

# Plot the probability of roosting in the wetland complex against the total precipitable water in the air column
ggplot(depart_final, aes(x=precip, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Precipitable water (kg/m^2)") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous(breaks=c(10,20, 30, 40, 50)) + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

# Plot the probability of roosting in the wetland complex against 6-hour averaged precipitation rate
ggplot(depart_final, aes(x=precip_mmh, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Precipitation rate (mm/h)") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous() + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

# Plot the probability of roosting in the wetland complex against the cloud cover
ggplot(depart_final, aes(x=cloud_cover, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Cloud cover") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous(breaks=c(0,25,50,75,100)) + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

ggplot(depart_final, aes(x=moon.fraction, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Moon illumination (%)") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous(breaks=c(0,25,50,75,100)) + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

ggplot(depart_final, aes(x=moon.phase, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Moon phase") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous() + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")

# Plot the probability of roosting in the wetland complex against the total illumination of the sky (1/cloud cover * lunar illumination)
ggplot(depart_final, aes(x=illum, y=roost)) + geom_point(size=4, alpha=0.5, colour="purple") + stat_smooth(method="glm", formula=y~x, method.args = list(family = "binomial"), colour="purple") + theme_bw() + xlab("Sky illumination (%)") + ylab("Probability of Roosting") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15)) + scale_x_continuous(breaks=c(0,25,50,75,100)) + scale_y_continuous(breaks=c(0,0.10,0.20,0.30,0.40,0.50,0.60,0.70,0.80,0.90,1)) + coord_cartesian(ylim=c(-0.01,1)) + theme(legend.position="none")


ggplot(depart_final) + 
  aes(ordinal_date, roost) +
  geom_col() +facet_grid(~sex)+
  scale_fill_identity(guide = "legend")+
  ylab("Count of birds roosting")+
  xlab("Ordinal date")

# ggplot(depart_final) +
#   aes(sex, roost) +
#   geom_col() +
#   scale_fill_identity(guide = "legend")+
#   ylab("Count of birds roosting")+
#   xlab("Sex")

################## 


```


``` {r}
m = glmer(roost ~ distance + sex + ordinal_date + sex:ordinal_date + illum + (1|colony/id), data=depart_final, family="binomial",na.action=na.omit)
```


``` {r}
# model has problems using unscaled data, use df.scale (df where distance and ordinal date were scaled and centered)
m = glmer(roost ~ distance + sex + ordinal_date + sex:ordinal_date + illum + (1|colony/id), data=df.scale, family="binomial",na.action=na.omit)

#examine normality of random variables (other plots form this function are problematic with binomial models)
check_model(m,check="normality")
check_model(m)

#check for over/under dispersion using DHARMa
testDispersion(m) #looks fine
dharm_output = simulateResiduals(fittedModel=m,plot = F)
plot(dharm_output) #this looks fine although the lack of deviation is weird - not much can be gathered from the overall residuals in a binomial model anyways - check individual variables
plotResiduals(dharm_output, form=df.scale$distance) #some overdispersion but not terrible, indicates possible non-linear relationship with distance
plotResiduals(dharm_output, form=df.scale$ordinal_date) #fine
plotResiduals(dharm_output, form=df.scale$sex) #fine
plotResiduals(dharm_output, form=df.scale$id) #some issues but not terrible
plotResiduals(dharm_output, form=df.scale$colony) #some issues but not terrible again

#see if transformation to distance helps fit - appears to be a log relationship but cannot take log of my distance variable (produces NAs and unscaled data does not converge) - try negative exponential, sqrt, adding a polynomial term

#sqrt 
m_exp = glmer(roost ~ exp(distance) + sex + ordinal_date + sex:ordinal_date + moon.phase + (1|colony/id), data=df.scale, family="binomial",na.action=na.omit)
plotResiduals(simulateResiduals(fittedModel=m_exp,plot = F), form=df.scale$distance) #fit is not much better

#neg exponential
m_neg = glmer(roost ~ exp(-distance) + sex + ordinal_date + sex:ordinal_date + moon.phase + (1|colony/id), data=df.scale, family="binomial",na.action=na.omit) 
plotResiduals(simulateResiduals(fittedModel=m_neg,plot = F), form=df.scale$distance) #fit is worse

#polynomial
m_sqrd = glmer(roost ~ distance+I(distance^2) + sex + ordinal_date + sex:ordinal_date + moon.phase + (1|colony/id), data=df.scale, family="binomial",na.action=na.omit)
plotResiduals(simulateResiduals(fittedModel=m_sqrd,plot = F), form=df.scale$distance) #fit is about the same


Anova(m,type=3)
summary(m)
df.scale$dist_logit_ypred <- -2.489848 -2.019687*df.scale$distance
df.scale$dist_logit_upper = df.scale$dist_logit_ypred+0.383874*2
df.scale$dist_logit_lower = df.scale$dist_logit_ypred-0.383874*2

depart_final$dist_ypred <- exp(df.scale$dist_logit_ypred) / (1 + exp(df.scale$dist_logit_ypred))
depart_final$dist_upper <- exp(df.scale$dist_logit_upper) / (1 + exp(df.scale$dist_logit_upper))
depart_final$dist_lower = exp(df.scale$dist_logit_lower) / (1 + exp(df.scale$dist_logit_lower))

plot(roost ~  jitter(distance), depart_final) + points(depart_final$distance, depart_final$dist_ypred, col="red", type = "l", lwd = 2)

ggplot(depart_final,aes(distance,dist_ypred,
               ymin=dist_lower,ymax=dist_upper,legend="FALSE",
               ))+
     geom_line()+theme(legend.position="none")+
     geom_ribbon(alpha=0.2,colour=NA)+ylab("Probability of roosting")+xlab("Distance to roost site (km)")+
     geom_rug(sides="b") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15))


str(m)
summary(m)
effects_m =allEffects(m)
str(effects_m)
plot(effects_m$illum)

effect_dist = as.data.frame(effects_m$distance)
effect_dist_unscaled = effect_dist
effect_dist_unscaled$distance = effect_dist$distance*scaleList_dist$scale + scaleList_dist$center
effect_dist_unscaled
ggplot(effect_dist_unscaled,aes(distance,fit,
               ymin=lower,ymax=upper,legend="FALSE",
               ))+
     geom_line()+theme(legend.position="none")+
     geom_ribbon(alpha=0.2,colour=NA)+ylab("Probability of roosting")+xlab("Distance to roost site (km)")+
     geom_rug(sides="b") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15))

plot(effects_m$'sex:ordinal_date')
str(effects_m$'sex:ordinal_date'$fit)
effect_date = as.data.frame(effects_m$'sex:ordinal_date')
effect_date_unscaled = effect_date
effect_date_unscaled$ordinal_date = effect_date$ordinal_date*scaleList_date$scale + scaleList_date$center
effect_date_unscaled

ggplot(effect_date_unscaled,aes(ordinal_date,fit,
               ymin=lower,ymax=upper,legend="FALSE",
               color = sex))+
     geom_line()+theme(legend.position="right")+
     geom_ribbon(alpha=0.2,colour=NA)+ylab("Probability of roosting")+xlab("Ordinal date")+facet_grid(~sex)+
     geom_rug(sides="b") + theme(strip.background = element_rect(fill="white"),axis.title.x=element_text(size=15, vjust=-0.4), axis.title.y=element_text(size=15, vjust=1.5), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15))


str(effects_m)
plot(effect("distance",m))
vif(m)
mean()
```

```{r, echo=FALSE}
############### plots of random effects
r1 <- as.data.frame(ranef(m, condVar = TRUE, whichel = c("id", "colony")))
p1 <- ggplot(subset(r1, grpvar == "id"), aes(y = grp, x = condval)) +
  geom_point() +
  geom_pointrange(
    aes(xmin = condval - condsd * 1.96, xmax = condval + condsd * 1.96)
  ) +
  geom_vline(aes(xintercept = 0, color = "red")) +
  theme_classic() +
  theme(legend.position = "none")
p2 <- ggplot(subset(r1, grpvar == "colony"), aes(y = grp, x = condval)) +
  geom_point() +
  geom_pointrange(
    aes(xmin = condval - condsd * 1.96, xmax = condval + condsd * 1.96)
  ) +
  geom_vline(aes(xintercept = 0, color = "red")) +
  theme_classic() +
  theme(legend.position = "none")
p1 + p2


r5 <- as.data.frame(ranef(m))
ggplot(data = r5, aes(sample = condval)) +
  geom_qq() + geom_qq_line() +
  facet_wrap(~ grpvar) +
  theme_classic()
```